spring:
  application:
    name: Authentication-Service
  data:
    mongodb:
      uri: mongodb+srv://222ruanpablo:<db_password>@wild-cerrado.j5fwh.mongodb.net/?retryWrites=true&w=majority&appName=wild-cerrado
      database: BookingDatabase